# apiVersion: podmig.dcn.ssu.ac.kr/v1
# kind: Podmigration
# metadata:
#   name: podmigration-sample
# spec:
#   # Add fields here
#   foo: bar
apiVersion: podmig.dcn.ssu.ac.kr/v1
kind: Podmigration
metadata:
  name: test2
  labels:
    name: test2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: video
      annotations:
        snapshotPolicy: "live-migration"
        #snapshotPath: "/var/lib/kubelet/migration"
        sourcePod: "video"
    spec:
      containers:
      - name: vlc
        image: lroktu/vlc-server:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        #args: ["big_buck_bunny.mp4","--loop","--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]
      nodeSelector:
        kubernetes.io/hostname: worker2
