# apiVersion: podmig.dcn.ssu.ac.kr/v1
# kind: Podmigration
# metadata:
#   name: podmigration-sample
# spec:
#   # Add fields here
#   foo: bar
apiVersion: podmig.dcn.ssu.ac.kr/v1
kind: Podmigration
metadata:
  name: test1
  labels:
    name: test1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple
      annotations:
        snapshotPolicy: "live-migration"
        #snapshotPath: "/var/lib/kubelet/migration"
        sourcePod: "simple"
        #sourcePod: "cccc"
    spec:
      containers:
      - name: count
        image: alpine
      nodeSelector:
        kubernetes.io/hostname: worker2
